version: '3.8'

services:
  pd-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    environment:
      - PORT=80
    volumes:
      - ../resources:/app/resources
    restart: unless-stopped
