apiVersion: v1
kind: Service
metadata:
  name: pd-inference-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  selector:
    app: pd-inference
